export const SET_TICKET_PRICE = "SET_TICKET_PRICE";
export const SET_MATCHE_ID = "SET_MATCHE_ID";
export const SET_TICKET_NUMBER = "SET_TICKET_NUMBER";
export const SET_MAX_TICKET_NUMBER = "SET_MAX_TICKET_NUMBER";
export const SET_MIN_TICKET_NUMBER = "SET_MIN_TICKET_NUMBER";
export const SET_TICKET_DEADLINE = "SET_TICKET_DEADLINE"; 
export const GET_MATCHE_DETAILS = "GET_MATCHE_DETAILS";