export const SET_OFFRE_TYPE = "SET_OFFRE_TYPE";
export const SET_OFFRE_TITLE = "SET_OFFRE_TITLE";
export const SET_OFFRE_IMAGE = "SET_OFFRE_IMAGE";
export const SET_OFFRE_PERCENTAGE = "SET_OFFRE_PERCENTAGE";
export const SET_OFFRE_PROMO_CODE = "SET_OFFRE_PROMO_CODE";
export const SET_OFFRE_EXPIRATION_DATE = "SET_OFFRE_EXPIRATION_DATE";
export const SET_OFFRE_HOUR = "SET_OFFRE_HOUR";
export const SET_OFFRE_MINUTE = "SET_OFFRE_MINUTE";
